version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: wine-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/data/db.sqlite3
    volumes:
      - ./logs:/app/logs
      - api-db:/app/data
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: wine-frontend
    ports:
      - "8501:80"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: always

volumes:
  api-db:
